source 'http://rubygems.org'
gem 'rails', '6.0.3'
gem 'mysql2', '0.5.3'
gem 'sprockets', '3.7.2'
gem 'globalid', '0.4.2'
gem 'puma'
gem 'sassc-rails'
gem 'uglifier', '>= 1.3.0'
gem 'execjs', '2.7.0'
gem 'therubyracer', platforms: :ruby
gem 'bootstrap', '~>4.0.0'
gem 'rexml'
gem 'nokogiri', '1.10.10'
gem 'loofah', '2.20.0'
gem 'twitter-typeahead-rails'
gem 'autoprefixer-rails', '8.6.5'
gem 'jquery-rails'
gem 'jquery-datatables'
gem 'jquery-turbolinks'
gem 'comfy_bootstrap_form'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-modal-rails'
gem 'font-awesome-rails'
gem 'activerecord-session_store'
gem 'best_in_place'
gem 'ledermann-rails-settings'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'json'
gem 'listen'
gem 'aws-sdk-dynamobd'
gem 'aws-sdk-lambda'
gem 'aws-sdk-s3'
gem 'aws-sdk-secretsmanager'
gem 'aws-sdk-ssm'
gem 'aws-sdk-sqs'
gem 'composite_primary_keys', '=12.0.8'
gem 'letter_avatar', '~> 0.3.7'
gem 'whenever', require: false
gem 'ipaddress'
gem 'rest-client'
gem 'caxlsx-rails'
gem 'sidekiq', '~> 6.5'
gem 'faraday'
gem 'faraday-follow-_redirects'
gem 'faraday-cookie_jar', ''
gem 'unf_ext', '=0.0.8.2'
gem 'image_processing', '~> 1.12.2'

group :development do
  gem 'web-console'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
end
